### ISSUE TITLE
Background scrolling issue

### ISSUE THREAD

**Issue by imalhasaranga** [Bobbyloujo/BobEngine#1]
Hi,
we have created 2d car game, and there the background should scroll,  game works fine in most devices but samsung S Dous and Samsung Grand prime it is not working

**Comment by Bobbyloujo** [comment]
That is a strange issue! Does everything else work fine one those devices? Does the background display at all?

**Comment by imalhasaranga** [comment]
I found the issue.. for some reason 
getRatioY and getRatioX returns 0 for those devices 

I did not went details to this issue but I put a temporary fix like this 

public double getRatioY() {
	double ratiox = getView().getRatioY();
	if(ratiox == 0){
		ratiox =  getView().getHeight()/1280.0;
	}
	return ratiox;
}

This is just a plaster to the real issue..  please instruct me when you have a fix

**Comment by Bobbyloujo** [comment]
Ah yes I remember someone else having a similar issue. I fixed it in an update. Are you using the most recent version of BobEngine? Check the updateRatioY() method in BobView.java. It should look like this:

	public void updateRatioY() {
		WindowManager wm = (WindowManager) getContext().getSystemService(Context.WINDOW_SERVICE);
		try {
			wm.getDefaultDisplay().getRealSize(screen);
		} catch (NoSuchMethodError e) {
			screen.y = wm.getDefaultDisplay().getHeight();
		}

		if(isPortrait()) ratioY = (double) screen.y / INIT_BASE_H;
		else ratioY = (double) screen.y / INIT_BASE_W;
	}

If this is what it looks like for you and you are still having this problem, please try casting INIT_BASE_H and INIT_BASE_W as (double) in both updateRatioY() and updateRatioX(). I think this will solve your problem. If it does, let me know and I will fix it for the next BobEngine update.
